name: "Deployment Status to Slack"
description: "Send deployment status updates to Slack"
author: "Your Name"

inputs:
  slack_token:
    description: "Slack bot user OAuth token"
    required: true
  slack_channel_id:
    description: "Slack channel ID to send the message to"
    required: true
  status:
    description: "Deployment status (started, success, failure)"
    required: true
  environment:
    description: "Deployment environment (e.g., production, staging)"
    required: true
  actor:
    description: "User who triggered the action"
    required: true
  run_id:
    description: "GitHub Actions run ID"
    required: true
  ts:
    description: "Slack message timestamp for updating an existing message"
    required: false

drivers:
  using: "node20"
  main: "index.js"